grails-app/domain/secretescapes/Account.groovy
package secretescapes

import groovy.transform.EqualsAndHashCode

@EqualsAndHashCode(includes='holderName, emailAddress')
class Account {

    String holderName
    Double balance = 200D
    String emailAddress

    static constraints = {
        emailAddress email:true
        balance min: 0D
    }

}

grails-app/domain/secretescapes/Payment.groovy
package secretescapes

class Payment {
    Account accountFrom
    Account accountTo
    Double amount

    // static belongsTo = [Account]

    static constraints = {
        amount validator: { val, obj ->
            if(val > obj.accountFrom?.balance){
                return ['overdraft']
            }
        }

        accountTo validator: { val, obj, errors ->
            if (obj.accountFrom == val) errors.rejectValue('accountTo', 'equals')
        }
    }

}

grails-app/controllers/secretescapes/AccountController.groovy
package secretescapes

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class AccountController {

    AccountService accountService
    PaymentService paymentService

    static allowedMethods = [save: "POST", update: "PUT"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond accountService.list(params), model:[accountCount: accountService.count()]
    }

    def show(Long id) {
        Account account = accountService.get(id)
        Collection payments = paymentService.listAccountPayments(account, params)
        Long paymentsCount = paymentService.countAccountPayments(account)

        respond account, model:[payments:payments, paymentsCount: paymentsCount]
    }

}

grails-app/controllers/secretescapes/PaymentController.groovy
package secretescapes

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*
import grails.plugins.mail.MailService

class PaymentController {

    PaymentService paymentService
    MailService mailService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond paymentService.list(params), model:[paymentCount: paymentService.count()]
    }

    def create() {
        respond new Payment(params),
            view:'pay', model:[accounts:Account.list(), accountFrom: Account.get(1), accountTo: Account.get(2)]
    }

    def save(Payment payment) {
        if (payment == null) {
            notFound()
            return
        }

        try {
            paymentService.save(payment)

            mailService.sendMail {
               to payment?.accountFrom?.emailAddress,payment?.accountTo?.emailAddress
               from "transfer@secretescapes.com"
               subject "Test transfer successful! (This is a test)"
               html "<h1>Transfer successful!</h1><b>From: </b>${payment?.accountFrom?.holderName}<br /><b>To: </b>${payment?.accountTo?.holderName}<br><b>Amount:</b> ${payment?.amount}"
            }

        } catch (ValidationException e) {
            respond payment.errors, view:'pay',
                model:[accounts:Account.list(), accountFrom: payment?.accountFrom, accountTo: payment?.accountTo]
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = "Transfer Successful"
                redirect controller:'account', action:'index', method:"GET"
            }
            '*' { respond payment, [status: CREATED] }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'payment.label', default: 'Payment'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/secretescapes/UrlMappings.groovy
package secretescapes

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(controller:"account", action:"index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico"/>

    <asset:javascript src="jquery-3.3.1.min.js"/>
    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-static-top" role="navigation">
    <a class="navbar-brand" href="/#"><asset:image src="se-logo-light.png" alt="Secret Escapes"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" aria-expanded="false" style="height: 0.8px;" id="navbarContent">
        <ul class="nav navbar-nav ml-auto">
            <g:pageProperty name="page.nav"/>
        </ul>
    </div>

</nav>

<g:layoutBody/>


<div id="spinner" class="spinner" style="display:none;">
    <g:message code="spinner.alt" default="Loading&hellip;"/>
</div>

<asset:javascript src="application.js"/>

</body>
</html>

grails-app/views/payment/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'payment.label', default: 'Payment')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-payment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-payment" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${paymentList}" />

            <div class="pagination">
                <g:paginate total="${paymentCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/payment/pay.gsp
<%@ page import="secretescapes.Account" %>

<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <title><%@ page import="secretescapes.Account" %></title>
    </head>
    <body>
        <div class="nav row" role="navigation">
            <div class="col-md">
                <a href="#create-payment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
                <ul>
                    <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                </ul>
            </div>
        </div>

        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${this.payment}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.payment}" var="error">
            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
        </g:hasErrors>

        <div id="create-payment" class="content scaffold-create row" role="main">
            <div class="col-md">
                <h2>Pay</h2>
                <g:form resource="${this.payment}" method="POST" class="needs-validation">
                    <fieldset class="form">
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Account From:</label>
                            <div class="col-sm-4">
                                <g:select name="accountFrom" class="form-control" from="${this.accounts}" optionKey="id" optionValue="holderName"
                                    value="${this.accountFrom?.id}"/>
                                <div class="invalid-feedback">Must be different</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Account To:</label>
                            <div class="col-sm-4">
                                <g:select name="accountTo" class="form-control" from="${this.accounts}" optionKey="id" optionValue="holderName"
                                    value="${this.accountTo?.id}" />
                                <div class="invalid-feedback">Must be different</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Amount:</label>
                            <div class="col-sm-4">
                                <g:field type="number" name="amount" class="form-control" required="true" value="${this.payment.amount}"  />
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="buttons">
                        <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                        <g:link class="delete" url="/" resource="${this.account}"><g:message code="default.cancel.label" default="Cancel" /></g:link>
                    </fieldset>
                </g:form>
            </div>
        </div>

        <script>
            $(document).ready(function(){
                $("select").change(function(){
                    let accountFrom = $("#accountFrom")
                    let accountTo = $("#accountTo")

                    if(accountFrom.val() == accountTo.val()){
                        accountFrom.addClass("is-invalid")
                        accountTo.addClass("is-invalid")
                    }else{
                        accountFrom.removeClass("is-invalid")
                        accountTo.removeClass("is-invalid")
                    }
                })
            });
        </script>

    </body>
</html>

grails-app/views/payment/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'payment.label', default: 'Payment')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-payment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-payment" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="payment" />
            <g:form resource="${this.payment}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.payment}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>